// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package GoogleGRPC_08.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GoogleGRPC_08.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GoogleGRPC_08.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<GoogleGRPC_08.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .GoogleGRPC_08.proto.StudentResponse studentResponse = 1;</code>
   */
  GoogleGRPC_08.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .GoogleGRPC_08.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .GoogleGRPC_08.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends GoogleGRPC_08.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .GoogleGRPC_08.proto.StudentResponse studentResponse = 1;</code>
   */
  GoogleGRPC_08.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
