// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package GoogleGRPC_08.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GoogleGRPC_08_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GoogleGRPC_08_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GoogleGRPC_08_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GoogleGRPC_08_proto_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\023GoogleGRPC_08.proto\"\035\n\t" +
      "MyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyRespons" +
      "e\022\020\n\010realname\030\002 \001(\t2l\n\016StudentService\022Z\n" +
      "\025GetRealNameByUsername\022\036.GoogleGRPC_08.p" +
      "roto.MyRequest\032\037.GoogleGRPC_08.proto.MyR" +
      "esponse\"\000B%\n\023GoogleGRPC_08.protoB\014Studen" +
      "tProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GoogleGRPC_08_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GoogleGRPC_08_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GoogleGRPC_08_proto_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_GoogleGRPC_08_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GoogleGRPC_08_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GoogleGRPC_08_proto_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
