// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package GoogleGRPC_08.proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GoogleGRPC_08.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();
}
