// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/Protobuf/Animal.proto

package GoogleProtobuf_06.Generate;

public final class AnimalInfo {
  private AnimalInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GoogleProtobuf_06.Generate.Type)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .GoogleProtobuf_06.Generate.Type.AnimalType a_t = 1;</code>
     * @return Whether the aT field is set.
     */
    boolean hasAT();
    /**
     * <code>required .GoogleProtobuf_06.Generate.Type.AnimalType a_t = 1;</code>
     * @return The aT.
     */
    GoogleProtobuf_06.Generate.AnimalInfo.Type.AnimalType getAT();

    /**
     * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
     * @return Whether the dog field is set.
     */
    boolean hasDog();
    /**
     * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
     * @return The dog.
     */
    GoogleProtobuf_06.Generate.AnimalInfo.Dog getDog();
    /**
     * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
     */
    GoogleProtobuf_06.Generate.AnimalInfo.DogOrBuilder getDogOrBuilder();

    /**
     * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
     * @return Whether the cat field is set.
     */
    boolean hasCat();
    /**
     * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
     * @return The cat.
     */
    GoogleProtobuf_06.Generate.AnimalInfo.Cat getCat();
    /**
     * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
     */
    GoogleProtobuf_06.Generate.AnimalInfo.CatOrBuilder getCatOrBuilder();

    public GoogleProtobuf_06.Generate.AnimalInfo.Type.AnimalBodyCase getAnimalBodyCase();
  }
  /**
   * Protobuf type {@code GoogleProtobuf_06.Generate.Type}
   */
  public  static final class Type extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GoogleProtobuf_06.Generate.Type)
      TypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Type.newBuilder() to construct.
    private Type(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Type() {
      aT_ = 1;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Type();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Type(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              GoogleProtobuf_06.Generate.AnimalInfo.Type.AnimalType value = GoogleProtobuf_06.Generate.AnimalInfo.Type.AnimalType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                aT_ = rawValue;
              }
              break;
            }
            case 18: {
              GoogleProtobuf_06.Generate.AnimalInfo.Dog.Builder subBuilder = null;
              if (animalBodyCase_ == 2) {
                subBuilder = ((GoogleProtobuf_06.Generate.AnimalInfo.Dog) animalBody_).toBuilder();
              }
              animalBody_ =
                  input.readMessage(GoogleProtobuf_06.Generate.AnimalInfo.Dog.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((GoogleProtobuf_06.Generate.AnimalInfo.Dog) animalBody_);
                animalBody_ = subBuilder.buildPartial();
              }
              animalBodyCase_ = 2;
              break;
            }
            case 26: {
              GoogleProtobuf_06.Generate.AnimalInfo.Cat.Builder subBuilder = null;
              if (animalBodyCase_ == 3) {
                subBuilder = ((GoogleProtobuf_06.Generate.AnimalInfo.Cat) animalBody_).toBuilder();
              }
              animalBody_ =
                  input.readMessage(GoogleProtobuf_06.Generate.AnimalInfo.Cat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((GoogleProtobuf_06.Generate.AnimalInfo.Cat) animalBody_);
                animalBody_ = subBuilder.buildPartial();
              }
              animalBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Type_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Type_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GoogleProtobuf_06.Generate.AnimalInfo.Type.class, GoogleProtobuf_06.Generate.AnimalInfo.Type.Builder.class);
    }

    /**
     * Protobuf enum {@code GoogleProtobuf_06.Generate.Type.AnimalType}
     */
    public enum AnimalType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DogType = 1;</code>
       */
      DogType(1),
      /**
       * <code>CatType = 2;</code>
       */
      CatType(2),
      ;

      /**
       * <code>DogType = 1;</code>
       */
      public static final int DogType_VALUE = 1;
      /**
       * <code>CatType = 2;</code>
       */
      public static final int CatType_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static AnimalType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static AnimalType forNumber(int value) {
        switch (value) {
          case 1: return DogType;
          case 2: return CatType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<AnimalType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          AnimalType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<AnimalType>() {
              public AnimalType findValueByNumber(int number) {
                return AnimalType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return GoogleProtobuf_06.Generate.AnimalInfo.Type.getDescriptor().getEnumTypes().get(0);
      }

      private static final AnimalType[] VALUES = values();

      public static AnimalType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private AnimalType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:GoogleProtobuf_06.Generate.Type.AnimalType)
    }

    private int bitField0_;
    private int animalBodyCase_ = 0;
    private java.lang.Object animalBody_;
    public enum AnimalBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      DOG(2),
      CAT(3),
      ANIMALBODY_NOT_SET(0);
      private final int value;
      private AnimalBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static AnimalBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static AnimalBodyCase forNumber(int value) {
        switch (value) {
          case 2: return DOG;
          case 3: return CAT;
          case 0: return ANIMALBODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public AnimalBodyCase
    getAnimalBodyCase() {
      return AnimalBodyCase.forNumber(
          animalBodyCase_);
    }

    public static final int A_T_FIELD_NUMBER = 1;
    private int aT_;
    /**
     * <code>required .GoogleProtobuf_06.Generate.Type.AnimalType a_t = 1;</code>
     * @return Whether the aT field is set.
     */
    public boolean hasAT() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .GoogleProtobuf_06.Generate.Type.AnimalType a_t = 1;</code>
     * @return The aT.
     */
    public GoogleProtobuf_06.Generate.AnimalInfo.Type.AnimalType getAT() {
      @SuppressWarnings("deprecation")
      GoogleProtobuf_06.Generate.AnimalInfo.Type.AnimalType result = GoogleProtobuf_06.Generate.AnimalInfo.Type.AnimalType.valueOf(aT_);
      return result == null ? GoogleProtobuf_06.Generate.AnimalInfo.Type.AnimalType.DogType : result;
    }

    public static final int DOG_FIELD_NUMBER = 2;
    /**
     * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
     * @return Whether the dog field is set.
     */
    public boolean hasDog() {
      return animalBodyCase_ == 2;
    }
    /**
     * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
     * @return The dog.
     */
    public GoogleProtobuf_06.Generate.AnimalInfo.Dog getDog() {
      if (animalBodyCase_ == 2) {
         return (GoogleProtobuf_06.Generate.AnimalInfo.Dog) animalBody_;
      }
      return GoogleProtobuf_06.Generate.AnimalInfo.Dog.getDefaultInstance();
    }
    /**
     * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
     */
    public GoogleProtobuf_06.Generate.AnimalInfo.DogOrBuilder getDogOrBuilder() {
      if (animalBodyCase_ == 2) {
         return (GoogleProtobuf_06.Generate.AnimalInfo.Dog) animalBody_;
      }
      return GoogleProtobuf_06.Generate.AnimalInfo.Dog.getDefaultInstance();
    }

    public static final int CAT_FIELD_NUMBER = 3;
    /**
     * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
     * @return Whether the cat field is set.
     */
    public boolean hasCat() {
      return animalBodyCase_ == 3;
    }
    /**
     * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
     * @return The cat.
     */
    public GoogleProtobuf_06.Generate.AnimalInfo.Cat getCat() {
      if (animalBodyCase_ == 3) {
         return (GoogleProtobuf_06.Generate.AnimalInfo.Cat) animalBody_;
      }
      return GoogleProtobuf_06.Generate.AnimalInfo.Cat.getDefaultInstance();
    }
    /**
     * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
     */
    public GoogleProtobuf_06.Generate.AnimalInfo.CatOrBuilder getCatOrBuilder() {
      if (animalBodyCase_ == 3) {
         return (GoogleProtobuf_06.Generate.AnimalInfo.Cat) animalBody_;
      }
      return GoogleProtobuf_06.Generate.AnimalInfo.Cat.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAT()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, aT_);
      }
      if (animalBodyCase_ == 2) {
        output.writeMessage(2, (GoogleProtobuf_06.Generate.AnimalInfo.Dog) animalBody_);
      }
      if (animalBodyCase_ == 3) {
        output.writeMessage(3, (GoogleProtobuf_06.Generate.AnimalInfo.Cat) animalBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, aT_);
      }
      if (animalBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (GoogleProtobuf_06.Generate.AnimalInfo.Dog) animalBody_);
      }
      if (animalBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (GoogleProtobuf_06.Generate.AnimalInfo.Cat) animalBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GoogleProtobuf_06.Generate.AnimalInfo.Type)) {
        return super.equals(obj);
      }
      GoogleProtobuf_06.Generate.AnimalInfo.Type other = (GoogleProtobuf_06.Generate.AnimalInfo.Type) obj;

      if (hasAT() != other.hasAT()) return false;
      if (hasAT()) {
        if (aT_ != other.aT_) return false;
      }
      if (!getAnimalBodyCase().equals(other.getAnimalBodyCase())) return false;
      switch (animalBodyCase_) {
        case 2:
          if (!getDog()
              .equals(other.getDog())) return false;
          break;
        case 3:
          if (!getCat()
              .equals(other.getCat())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAT()) {
        hash = (37 * hash) + A_T_FIELD_NUMBER;
        hash = (53 * hash) + aT_;
      }
      switch (animalBodyCase_) {
        case 2:
          hash = (37 * hash) + DOG_FIELD_NUMBER;
          hash = (53 * hash) + getDog().hashCode();
          break;
        case 3:
          hash = (37 * hash) + CAT_FIELD_NUMBER;
          hash = (53 * hash) + getCat().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GoogleProtobuf_06.Generate.AnimalInfo.Type parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Type parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Type parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Type parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Type parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Type parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Type parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Type parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Type parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Type parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Type parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Type parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GoogleProtobuf_06.Generate.AnimalInfo.Type prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GoogleProtobuf_06.Generate.Type}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GoogleProtobuf_06.Generate.Type)
        GoogleProtobuf_06.Generate.AnimalInfo.TypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Type_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Type_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GoogleProtobuf_06.Generate.AnimalInfo.Type.class, GoogleProtobuf_06.Generate.AnimalInfo.Type.Builder.class);
      }

      // Construct using GoogleProtobuf_06.Generate.AnimalInfo.Type.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        aT_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        animalBodyCase_ = 0;
        animalBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Type_descriptor;
      }

      @java.lang.Override
      public GoogleProtobuf_06.Generate.AnimalInfo.Type getDefaultInstanceForType() {
        return GoogleProtobuf_06.Generate.AnimalInfo.Type.getDefaultInstance();
      }

      @java.lang.Override
      public GoogleProtobuf_06.Generate.AnimalInfo.Type build() {
        GoogleProtobuf_06.Generate.AnimalInfo.Type result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GoogleProtobuf_06.Generate.AnimalInfo.Type buildPartial() {
        GoogleProtobuf_06.Generate.AnimalInfo.Type result = new GoogleProtobuf_06.Generate.AnimalInfo.Type(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.aT_ = aT_;
        if (animalBodyCase_ == 2) {
          if (dogBuilder_ == null) {
            result.animalBody_ = animalBody_;
          } else {
            result.animalBody_ = dogBuilder_.build();
          }
        }
        if (animalBodyCase_ == 3) {
          if (catBuilder_ == null) {
            result.animalBody_ = animalBody_;
          } else {
            result.animalBody_ = catBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.animalBodyCase_ = animalBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GoogleProtobuf_06.Generate.AnimalInfo.Type) {
          return mergeFrom((GoogleProtobuf_06.Generate.AnimalInfo.Type)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GoogleProtobuf_06.Generate.AnimalInfo.Type other) {
        if (other == GoogleProtobuf_06.Generate.AnimalInfo.Type.getDefaultInstance()) return this;
        if (other.hasAT()) {
          setAT(other.getAT());
        }
        switch (other.getAnimalBodyCase()) {
          case DOG: {
            mergeDog(other.getDog());
            break;
          }
          case CAT: {
            mergeCat(other.getCat());
            break;
          }
          case ANIMALBODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAT()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GoogleProtobuf_06.Generate.AnimalInfo.Type parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GoogleProtobuf_06.Generate.AnimalInfo.Type) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int animalBodyCase_ = 0;
      private java.lang.Object animalBody_;
      public AnimalBodyCase
          getAnimalBodyCase() {
        return AnimalBodyCase.forNumber(
            animalBodyCase_);
      }

      public Builder clearAnimalBody() {
        animalBodyCase_ = 0;
        animalBody_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int aT_ = 1;
      /**
       * <code>required .GoogleProtobuf_06.Generate.Type.AnimalType a_t = 1;</code>
       * @return Whether the aT field is set.
       */
      public boolean hasAT() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .GoogleProtobuf_06.Generate.Type.AnimalType a_t = 1;</code>
       * @return The aT.
       */
      public GoogleProtobuf_06.Generate.AnimalInfo.Type.AnimalType getAT() {
        @SuppressWarnings("deprecation")
        GoogleProtobuf_06.Generate.AnimalInfo.Type.AnimalType result = GoogleProtobuf_06.Generate.AnimalInfo.Type.AnimalType.valueOf(aT_);
        return result == null ? GoogleProtobuf_06.Generate.AnimalInfo.Type.AnimalType.DogType : result;
      }
      /**
       * <code>required .GoogleProtobuf_06.Generate.Type.AnimalType a_t = 1;</code>
       * @param value The aT to set.
       * @return This builder for chaining.
       */
      public Builder setAT(GoogleProtobuf_06.Generate.AnimalInfo.Type.AnimalType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        aT_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .GoogleProtobuf_06.Generate.Type.AnimalType a_t = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAT() {
        bitField0_ = (bitField0_ & ~0x00000001);
        aT_ = 1;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          GoogleProtobuf_06.Generate.AnimalInfo.Dog, GoogleProtobuf_06.Generate.AnimalInfo.Dog.Builder, GoogleProtobuf_06.Generate.AnimalInfo.DogOrBuilder> dogBuilder_;
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
       * @return Whether the dog field is set.
       */
      public boolean hasDog() {
        return animalBodyCase_ == 2;
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
       * @return The dog.
       */
      public GoogleProtobuf_06.Generate.AnimalInfo.Dog getDog() {
        if (dogBuilder_ == null) {
          if (animalBodyCase_ == 2) {
            return (GoogleProtobuf_06.Generate.AnimalInfo.Dog) animalBody_;
          }
          return GoogleProtobuf_06.Generate.AnimalInfo.Dog.getDefaultInstance();
        } else {
          if (animalBodyCase_ == 2) {
            return dogBuilder_.getMessage();
          }
          return GoogleProtobuf_06.Generate.AnimalInfo.Dog.getDefaultInstance();
        }
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
       */
      public Builder setDog(GoogleProtobuf_06.Generate.AnimalInfo.Dog value) {
        if (dogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          animalBody_ = value;
          onChanged();
        } else {
          dogBuilder_.setMessage(value);
        }
        animalBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
       */
      public Builder setDog(
          GoogleProtobuf_06.Generate.AnimalInfo.Dog.Builder builderForValue) {
        if (dogBuilder_ == null) {
          animalBody_ = builderForValue.build();
          onChanged();
        } else {
          dogBuilder_.setMessage(builderForValue.build());
        }
        animalBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
       */
      public Builder mergeDog(GoogleProtobuf_06.Generate.AnimalInfo.Dog value) {
        if (dogBuilder_ == null) {
          if (animalBodyCase_ == 2 &&
              animalBody_ != GoogleProtobuf_06.Generate.AnimalInfo.Dog.getDefaultInstance()) {
            animalBody_ = GoogleProtobuf_06.Generate.AnimalInfo.Dog.newBuilder((GoogleProtobuf_06.Generate.AnimalInfo.Dog) animalBody_)
                .mergeFrom(value).buildPartial();
          } else {
            animalBody_ = value;
          }
          onChanged();
        } else {
          if (animalBodyCase_ == 2) {
            dogBuilder_.mergeFrom(value);
          }
          dogBuilder_.setMessage(value);
        }
        animalBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
       */
      public Builder clearDog() {
        if (dogBuilder_ == null) {
          if (animalBodyCase_ == 2) {
            animalBodyCase_ = 0;
            animalBody_ = null;
            onChanged();
          }
        } else {
          if (animalBodyCase_ == 2) {
            animalBodyCase_ = 0;
            animalBody_ = null;
          }
          dogBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
       */
      public GoogleProtobuf_06.Generate.AnimalInfo.Dog.Builder getDogBuilder() {
        return getDogFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
       */
      public GoogleProtobuf_06.Generate.AnimalInfo.DogOrBuilder getDogOrBuilder() {
        if ((animalBodyCase_ == 2) && (dogBuilder_ != null)) {
          return dogBuilder_.getMessageOrBuilder();
        } else {
          if (animalBodyCase_ == 2) {
            return (GoogleProtobuf_06.Generate.AnimalInfo.Dog) animalBody_;
          }
          return GoogleProtobuf_06.Generate.AnimalInfo.Dog.getDefaultInstance();
        }
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Dog dog = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GoogleProtobuf_06.Generate.AnimalInfo.Dog, GoogleProtobuf_06.Generate.AnimalInfo.Dog.Builder, GoogleProtobuf_06.Generate.AnimalInfo.DogOrBuilder> 
          getDogFieldBuilder() {
        if (dogBuilder_ == null) {
          if (!(animalBodyCase_ == 2)) {
            animalBody_ = GoogleProtobuf_06.Generate.AnimalInfo.Dog.getDefaultInstance();
          }
          dogBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GoogleProtobuf_06.Generate.AnimalInfo.Dog, GoogleProtobuf_06.Generate.AnimalInfo.Dog.Builder, GoogleProtobuf_06.Generate.AnimalInfo.DogOrBuilder>(
                  (GoogleProtobuf_06.Generate.AnimalInfo.Dog) animalBody_,
                  getParentForChildren(),
                  isClean());
          animalBody_ = null;
        }
        animalBodyCase_ = 2;
        onChanged();;
        return dogBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          GoogleProtobuf_06.Generate.AnimalInfo.Cat, GoogleProtobuf_06.Generate.AnimalInfo.Cat.Builder, GoogleProtobuf_06.Generate.AnimalInfo.CatOrBuilder> catBuilder_;
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
       * @return Whether the cat field is set.
       */
      public boolean hasCat() {
        return animalBodyCase_ == 3;
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
       * @return The cat.
       */
      public GoogleProtobuf_06.Generate.AnimalInfo.Cat getCat() {
        if (catBuilder_ == null) {
          if (animalBodyCase_ == 3) {
            return (GoogleProtobuf_06.Generate.AnimalInfo.Cat) animalBody_;
          }
          return GoogleProtobuf_06.Generate.AnimalInfo.Cat.getDefaultInstance();
        } else {
          if (animalBodyCase_ == 3) {
            return catBuilder_.getMessage();
          }
          return GoogleProtobuf_06.Generate.AnimalInfo.Cat.getDefaultInstance();
        }
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
       */
      public Builder setCat(GoogleProtobuf_06.Generate.AnimalInfo.Cat value) {
        if (catBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          animalBody_ = value;
          onChanged();
        } else {
          catBuilder_.setMessage(value);
        }
        animalBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
       */
      public Builder setCat(
          GoogleProtobuf_06.Generate.AnimalInfo.Cat.Builder builderForValue) {
        if (catBuilder_ == null) {
          animalBody_ = builderForValue.build();
          onChanged();
        } else {
          catBuilder_.setMessage(builderForValue.build());
        }
        animalBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
       */
      public Builder mergeCat(GoogleProtobuf_06.Generate.AnimalInfo.Cat value) {
        if (catBuilder_ == null) {
          if (animalBodyCase_ == 3 &&
              animalBody_ != GoogleProtobuf_06.Generate.AnimalInfo.Cat.getDefaultInstance()) {
            animalBody_ = GoogleProtobuf_06.Generate.AnimalInfo.Cat.newBuilder((GoogleProtobuf_06.Generate.AnimalInfo.Cat) animalBody_)
                .mergeFrom(value).buildPartial();
          } else {
            animalBody_ = value;
          }
          onChanged();
        } else {
          if (animalBodyCase_ == 3) {
            catBuilder_.mergeFrom(value);
          }
          catBuilder_.setMessage(value);
        }
        animalBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
       */
      public Builder clearCat() {
        if (catBuilder_ == null) {
          if (animalBodyCase_ == 3) {
            animalBodyCase_ = 0;
            animalBody_ = null;
            onChanged();
          }
        } else {
          if (animalBodyCase_ == 3) {
            animalBodyCase_ = 0;
            animalBody_ = null;
          }
          catBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
       */
      public GoogleProtobuf_06.Generate.AnimalInfo.Cat.Builder getCatBuilder() {
        return getCatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
       */
      public GoogleProtobuf_06.Generate.AnimalInfo.CatOrBuilder getCatOrBuilder() {
        if ((animalBodyCase_ == 3) && (catBuilder_ != null)) {
          return catBuilder_.getMessageOrBuilder();
        } else {
          if (animalBodyCase_ == 3) {
            return (GoogleProtobuf_06.Generate.AnimalInfo.Cat) animalBody_;
          }
          return GoogleProtobuf_06.Generate.AnimalInfo.Cat.getDefaultInstance();
        }
      }
      /**
       * <code>optional .GoogleProtobuf_06.Generate.Cat cat = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GoogleProtobuf_06.Generate.AnimalInfo.Cat, GoogleProtobuf_06.Generate.AnimalInfo.Cat.Builder, GoogleProtobuf_06.Generate.AnimalInfo.CatOrBuilder> 
          getCatFieldBuilder() {
        if (catBuilder_ == null) {
          if (!(animalBodyCase_ == 3)) {
            animalBody_ = GoogleProtobuf_06.Generate.AnimalInfo.Cat.getDefaultInstance();
          }
          catBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GoogleProtobuf_06.Generate.AnimalInfo.Cat, GoogleProtobuf_06.Generate.AnimalInfo.Cat.Builder, GoogleProtobuf_06.Generate.AnimalInfo.CatOrBuilder>(
                  (GoogleProtobuf_06.Generate.AnimalInfo.Cat) animalBody_,
                  getParentForChildren(),
                  isClean());
          animalBody_ = null;
        }
        animalBodyCase_ = 3;
        onChanged();;
        return catBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GoogleProtobuf_06.Generate.Type)
    }

    // @@protoc_insertion_point(class_scope:GoogleProtobuf_06.Generate.Type)
    private static final GoogleProtobuf_06.Generate.AnimalInfo.Type DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GoogleProtobuf_06.Generate.AnimalInfo.Type();
    }

    public static GoogleProtobuf_06.Generate.AnimalInfo.Type getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Type>
        PARSER = new com.google.protobuf.AbstractParser<Type>() {
      @java.lang.Override
      public Type parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Type(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Type> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Type> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GoogleProtobuf_06.Generate.AnimalInfo.Type getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GoogleProtobuf_06.Generate.Dog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code GoogleProtobuf_06.Generate.Dog}
   */
  public  static final class Dog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GoogleProtobuf_06.Generate.Dog)
      DogOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dog.newBuilder() to construct.
    private Dog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dog() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Dog();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Dog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Dog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Dog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GoogleProtobuf_06.Generate.AnimalInfo.Dog.class, GoogleProtobuf_06.Generate.AnimalInfo.Dog.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GoogleProtobuf_06.Generate.AnimalInfo.Dog)) {
        return super.equals(obj);
      }
      GoogleProtobuf_06.Generate.AnimalInfo.Dog other = (GoogleProtobuf_06.Generate.AnimalInfo.Dog) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GoogleProtobuf_06.Generate.AnimalInfo.Dog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Dog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Dog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Dog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Dog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Dog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Dog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Dog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Dog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Dog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Dog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Dog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GoogleProtobuf_06.Generate.AnimalInfo.Dog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GoogleProtobuf_06.Generate.Dog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GoogleProtobuf_06.Generate.Dog)
        GoogleProtobuf_06.Generate.AnimalInfo.DogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Dog_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Dog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GoogleProtobuf_06.Generate.AnimalInfo.Dog.class, GoogleProtobuf_06.Generate.AnimalInfo.Dog.Builder.class);
      }

      // Construct using GoogleProtobuf_06.Generate.AnimalInfo.Dog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Dog_descriptor;
      }

      @java.lang.Override
      public GoogleProtobuf_06.Generate.AnimalInfo.Dog getDefaultInstanceForType() {
        return GoogleProtobuf_06.Generate.AnimalInfo.Dog.getDefaultInstance();
      }

      @java.lang.Override
      public GoogleProtobuf_06.Generate.AnimalInfo.Dog build() {
        GoogleProtobuf_06.Generate.AnimalInfo.Dog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GoogleProtobuf_06.Generate.AnimalInfo.Dog buildPartial() {
        GoogleProtobuf_06.Generate.AnimalInfo.Dog result = new GoogleProtobuf_06.Generate.AnimalInfo.Dog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GoogleProtobuf_06.Generate.AnimalInfo.Dog) {
          return mergeFrom((GoogleProtobuf_06.Generate.AnimalInfo.Dog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GoogleProtobuf_06.Generate.AnimalInfo.Dog other) {
        if (other == GoogleProtobuf_06.Generate.AnimalInfo.Dog.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GoogleProtobuf_06.Generate.AnimalInfo.Dog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GoogleProtobuf_06.Generate.AnimalInfo.Dog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       * @return Whether the age field is set.
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return The age.
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GoogleProtobuf_06.Generate.Dog)
    }

    // @@protoc_insertion_point(class_scope:GoogleProtobuf_06.Generate.Dog)
    private static final GoogleProtobuf_06.Generate.AnimalInfo.Dog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GoogleProtobuf_06.Generate.AnimalInfo.Dog();
    }

    public static GoogleProtobuf_06.Generate.AnimalInfo.Dog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Dog>
        PARSER = new com.google.protobuf.AbstractParser<Dog>() {
      @java.lang.Override
      public Dog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dog> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GoogleProtobuf_06.Generate.AnimalInfo.Dog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GoogleProtobuf_06.Generate.Cat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string color = 1;</code>
     * @return Whether the color field is set.
     */
    boolean hasColor();
    /**
     * <code>optional string color = 1;</code>
     * @return The color.
     */
    java.lang.String getColor();
    /**
     * <code>optional string color = 1;</code>
     * @return The bytes for color.
     */
    com.google.protobuf.ByteString
        getColorBytes();

    /**
     * <code>optional string address = 2;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 2;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 2;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code GoogleProtobuf_06.Generate.Cat}
   */
  public  static final class Cat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GoogleProtobuf_06.Generate.Cat)
      CatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Cat.newBuilder() to construct.
    private Cat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Cat() {
      color_ = "";
      address_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Cat();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Cat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              color_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              address_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Cat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Cat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GoogleProtobuf_06.Generate.AnimalInfo.Cat.class, GoogleProtobuf_06.Generate.AnimalInfo.Cat.Builder.class);
    }

    private int bitField0_;
    public static final int COLOR_FIELD_NUMBER = 1;
    private volatile java.lang.Object color_;
    /**
     * <code>optional string color = 1;</code>
     * @return Whether the color field is set.
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string color = 1;</code>
     * @return The color.
     */
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          color_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string color = 1;</code>
     * @return The bytes for color.
     */
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object address_;
    /**
     * <code>optional string address = 2;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string address = 2;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 2;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, color_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, address_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, color_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GoogleProtobuf_06.Generate.AnimalInfo.Cat)) {
        return super.equals(obj);
      }
      GoogleProtobuf_06.Generate.AnimalInfo.Cat other = (GoogleProtobuf_06.Generate.AnimalInfo.Cat) obj;

      if (hasColor() != other.hasColor()) return false;
      if (hasColor()) {
        if (!getColor()
            .equals(other.getColor())) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasColor()) {
        hash = (37 * hash) + COLOR_FIELD_NUMBER;
        hash = (53 * hash) + getColor().hashCode();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GoogleProtobuf_06.Generate.AnimalInfo.Cat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Cat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Cat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Cat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Cat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Cat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Cat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Cat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Cat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Cat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Cat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GoogleProtobuf_06.Generate.AnimalInfo.Cat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GoogleProtobuf_06.Generate.AnimalInfo.Cat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GoogleProtobuf_06.Generate.Cat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GoogleProtobuf_06.Generate.Cat)
        GoogleProtobuf_06.Generate.AnimalInfo.CatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Cat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Cat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GoogleProtobuf_06.Generate.AnimalInfo.Cat.class, GoogleProtobuf_06.Generate.AnimalInfo.Cat.Builder.class);
      }

      // Construct using GoogleProtobuf_06.Generate.AnimalInfo.Cat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        color_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GoogleProtobuf_06.Generate.AnimalInfo.internal_static_GoogleProtobuf_06_Generate_Cat_descriptor;
      }

      @java.lang.Override
      public GoogleProtobuf_06.Generate.AnimalInfo.Cat getDefaultInstanceForType() {
        return GoogleProtobuf_06.Generate.AnimalInfo.Cat.getDefaultInstance();
      }

      @java.lang.Override
      public GoogleProtobuf_06.Generate.AnimalInfo.Cat build() {
        GoogleProtobuf_06.Generate.AnimalInfo.Cat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GoogleProtobuf_06.Generate.AnimalInfo.Cat buildPartial() {
        GoogleProtobuf_06.Generate.AnimalInfo.Cat result = new GoogleProtobuf_06.Generate.AnimalInfo.Cat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.color_ = color_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GoogleProtobuf_06.Generate.AnimalInfo.Cat) {
          return mergeFrom((GoogleProtobuf_06.Generate.AnimalInfo.Cat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GoogleProtobuf_06.Generate.AnimalInfo.Cat other) {
        if (other == GoogleProtobuf_06.Generate.AnimalInfo.Cat.getDefaultInstance()) return this;
        if (other.hasColor()) {
          bitField0_ |= 0x00000001;
          color_ = other.color_;
          onChanged();
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000002;
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GoogleProtobuf_06.Generate.AnimalInfo.Cat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GoogleProtobuf_06.Generate.AnimalInfo.Cat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object color_ = "";
      /**
       * <code>optional string color = 1;</code>
       * @return Whether the color field is set.
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string color = 1;</code>
       * @return The color.
       */
      public java.lang.String getColor() {
        java.lang.Object ref = color_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            color_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string color = 1;</code>
       * @return The bytes for color.
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        java.lang.Object ref = color_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string color = 1;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string color = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        color_ = getDefaultInstance().getColor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string color = 1;</code>
       * @param value The bytes for color to set.
       * @return This builder for chaining.
       */
      public Builder setColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        color_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 2;</code>
       * @return Whether the address field is set.
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string address = 2;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 2;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 2;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 2;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        address_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GoogleProtobuf_06.Generate.Cat)
    }

    // @@protoc_insertion_point(class_scope:GoogleProtobuf_06.Generate.Cat)
    private static final GoogleProtobuf_06.Generate.AnimalInfo.Cat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GoogleProtobuf_06.Generate.AnimalInfo.Cat();
    }

    public static GoogleProtobuf_06.Generate.AnimalInfo.Cat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Cat>
        PARSER = new com.google.protobuf.AbstractParser<Cat>() {
      @java.lang.Override
      public Cat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Cat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GoogleProtobuf_06.Generate.AnimalInfo.Cat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GoogleProtobuf_06_Generate_Type_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GoogleProtobuf_06_Generate_Type_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GoogleProtobuf_06_Generate_Dog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GoogleProtobuf_06_Generate_Dog_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GoogleProtobuf_06_Generate_Cat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GoogleProtobuf_06_Generate_Cat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(src/main/resources/Protobuf/Animal.pro" +
      "to\022\032GoogleProtobuf_06.Generate\"\326\001\n\004Type\022" +
      "8\n\003a_t\030\001 \002(\0162+.GoogleProtobuf_06.Generat" +
      "e.Type.AnimalType\022.\n\003dog\030\002 \001(\0132\037.GoogleP" +
      "rotobuf_06.Generate.DogH\000\022.\n\003cat\030\003 \001(\0132\037" +
      ".GoogleProtobuf_06.Generate.CatH\000\"&\n\nAni" +
      "malType\022\013\n\007DogType\020\001\022\013\n\007CatType\020\002B\014\n\nAni" +
      "malBody\" \n\003Dog\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(" +
      "\005\"%\n\003Cat\022\r\n\005color\030\001 \001(\t\022\017\n\007address\030\002 \001(\t" +
      "B*\n\032GoogleProtobuf_06.GenerateB\nAnimalIn" +
      "foH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GoogleProtobuf_06_Generate_Type_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GoogleProtobuf_06_Generate_Type_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GoogleProtobuf_06_Generate_Type_descriptor,
        new java.lang.String[] { "AT", "Dog", "Cat", "AnimalBody", });
    internal_static_GoogleProtobuf_06_Generate_Dog_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GoogleProtobuf_06_Generate_Dog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GoogleProtobuf_06_Generate_Dog_descriptor,
        new java.lang.String[] { "Name", "Age", });
    internal_static_GoogleProtobuf_06_Generate_Cat_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GoogleProtobuf_06_Generate_Cat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GoogleProtobuf_06_Generate_Cat_descriptor,
        new java.lang.String[] { "Color", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
